archives/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('upload', views.upload, name='upload'),
    path('', views.dashboard, name='home'),
    path('student',views.student,name='student'),
    path('student_od',views.student_od,name='student_od'),
    path('staff',views.staff,name='staff'),
    path('department',views.department,name='department'),
    path('login',views.login,name='login'),
    path('resetpassword/<str:pk>',views.reset_password,name='resetpassword'),
    path('logout/',views.logout,name='logout'),
    path('level/',views.level,name='level'),
    path('delete_level/<str:pk>',views.delete_level,name='delete_level'),
    path('update_level/<str:pk>',views.update_level,name='update_level'),
    path('project_type',views.project_type,name='project_type'),
    path('pdf_upload/',views.pdf_upload,name='pdf_upload'),
    path('preview_pdf/<str:pk>',views.preview_pdf,name='preview_pdf'),
    path('addstaff',views.addstaff,name='addstaff'), 
    path('editstaff/<str:pk>',views.editstaff,name='editstaff'),
    path('addprojecttype',views.addprojecttype,name='addprojecttype'),
    path('editprojecttype/<str:pk>',views.editprojecttype,name='editprojecttype'),
    path('deleteprojecttype/<str:pk>',views.deleteprojecttype,name='deleteprojecttype'),
    path('upload_addstaff',views.upload_addstaff,name='upload_addstaff'),
    path('subtime',views.submissionTime,name='subtime'),
    path('addlevel',views.addlevel,name='addlevel'),
    path('projects',views.projects,name='projects'),
    path('editstudent/<str:pk>',views.editstudent,name='editstudent'),
    path('editdepartment/<str:pk>',views.editdepartment,name='editdepartment'),
    path('deletedepartment/<str:pk>',views.deletedepartment,name='deletedepartment'),
    path('blockuser/<str:pk>',views.blockuser,name='blockuser'),
    path('upload', views.upload, name='upload'),
    path('editlevel/<str:pk>',views.editlevel,name='editlevel'),
    path('deletelevel/<str:pk>',views.deletelevel,name='deletelevel'),
    path('upload_student',views.upload_student,name='upload_student'),
    path('q',views.my_view,name='my_view'),
    path('get_project_types/<str:department>',views.get_project_types,name='get_project_types'),
    path('deletestudent/<str:pk>',views.deletestudent,name='deletestudent'),
    path('deletepdf/<str:pk>',views.deletepdf,name='deletepdf'),
    path('addstudent',views.addstudent,name='addstudent'),
    path('manage_project',views.manage_project,name='manage_project'),
    path('changepassword',views.changepassword,name='changepassword'),
    # path('changedoctorpassword/<str:pk>',views.changedoctorpassword,name='changedoctorpassword'),
    path("manageroles",views.manageroles,name="manageroles"),
    path("addroles",views.addroles,name="addroles"),
    path("deleteroles/<str:pk>",views.deleteroles,name="deleteroles"),
    path("editroles/<str:pk>",views.editroles,name="editroles"),
    path('get_courses/', views.get_courses, name='get_courses'),
    # path("edit_speciality/<str:pk>",views.edit_speciality,name="edit_speciality"),
    # path("delete_speciality/<str:pk>",views.delete_speciality,name="delete_speciality"),
    path('save_pdf', views.save_pdf, name='save_pdf'),
    # path("deadline",views.deadline,name="deadline"),
    path("deadlines",views.deadlines,name="deadlines"),
    path("deletesub/<str:pk>",views.deletesub,name="deletesub"),
    path("assessment",views.assessment,name="assessment"),
    path("editsubtime/<str:pk>",views.editSubmittionTime,name="editsubtime"),
    path('progress',views.progress,name='progress'),
 
    # path('deletedoctorschedule/<str:pk>',views.deletedoctorschedule,name='deletedoctorschedule'),
    # path('editdoctorschedule/<str:pk>',views.editdoctorschedule,name='editdoctorschedule'),
    # path('makeappointment/<str:pk>',views.makeappointment,name='makeappointment'),
    # path('approve_appointment/<str:pk>',views.approve_appointment,name='approve_appointment'),
    # path('delete_appointment/<str:pk>',views.delete_appointment,name='delete_appointment'),
    # path('cancellappointment/<str:pk>',views.cancellappointment,name='cancellappointment'),
    
    # #doctor/////////////////////////////
    
    # path('doctordashboard',views.doctordashboard,name='doctordashboard'),
    # path('registerdoctor',views.registerdoctor,name='registerdoctor'),
    # path('doctorappointment',views.doctorappointment,name='doctorappointment'),
    # path('mypatient',views.mypatient,name='mypatient'),
    
    # path('doctorprofile',views.doctorprofile,name='doctorprofile'),
    # path('doctorchangepassword',views.doctorchangepassword,name='doctorchangepassword'),
     
    # #Patient //////////////////////////////////
    
    # path('patientdashboard',views.patientdashboard,name='patientdashboard'),
    # path('mydoctor',views.mydoctor,name='mydoctor'),
    # path('patient',views.patientprofile,name='patientprofile'),
    # path('patientprofile',views.patientprofile,name='patientprofile'),
    # path('patientchangepassword',views.patientchangepassword,name='patientchangepassword'),
    # path('booking',views.booking,name='booking'),
    # #  path('photopatient',views.photopatient,name='photopatient'),
    
     
     
]

projectArchives/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('archives.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archives/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.


# class User(AbstractUser):
#     class Meta:
#         db_table = 'users'
date =  datetime.datetime.now().year
first = str(date-1)
date = str(date)

date = f'{first}/{date}'
class Level(models.Model):
    name = models.CharField(max_length=30)
    date_created = models.DateField(auto_now_add=True)
    
    
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Level"
class Department(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Department"
        
class Awards(models.Model):
    name = models.CharField(max_length=100)
    level = models.ForeignKey(Level,on_delete=models.CASCADE)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "Awards"
   
class Student(models.Model):
    GENDER = (('Male','Male'),('Female','Female'))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(choices=GENDER, max_length=20)
    regNo =  models.CharField(unique=True,max_length=14)
    NTA_Level = models.IntegerField(null=True,blank=True)
    level = models.ForeignKey(Level,null=True,blank=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department,null=True,on_delete=models.CASCADE)
    academic_year = models.CharField(max_length=12)
    mobile = models.CharField(max_length=14, null=True,blank=True)
    photo = models.ImageField(upload_to='profile_pic',default='default.jpg', null=True, blank=True)
    course = models.CharField(max_length=100)
    
    def __str__(self):
        return self.regNo

    class Meta:
        db_table = "Student"
        

class Staff(models.Model):
    GENDER = (('Male','Male'),('Female','Female'))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(choices=GENDER, max_length=20)
    staff_id =  models.IntegerField(unique=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    mobile = models.TextField(max_length=14, null=True,blank=True)
    photo = models.ImageField(upload_to='profile_pic/staff',default='default.jpg', null=True, blank=True)
    level = models.ForeignKey(Level,null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name

    class Meta:
        db_table = "Staff"
        
        
class Project_type(models.Model):
    name = models.CharField(max_length=30)
    date_created = models.DateField(auto_now_add=True)
    department= models.ForeignKey(Department,null=True,blank=True,on_delete=models.CASCADE)    
    def __str__(self):
        return self.name

    class Meta:
        db_table = "project_type"
        
class Project(models.Model):
    title = models.CharField(null=True,blank=True,max_length=200)
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    project_type = models.ForeignKey(Project_type,on_delete=models.CASCADE,null=True,blank=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE,null=True,blank=True)
    date_created = models.DateField(auto_now_add=True)
    
    
    def __str__(self):
        return self.title

    class Meta:
        db_table = "project"



class Document(models.Model):
    project = models.OneToOneField(Project,null=True, blank=True, on_delete=models.CASCADE)
    file = models.FileField(upload_to='projects',null=True,blank=True)
    preview = models.FileField(upload_to='preview',null=True,blank=True)
    submitted = models.BooleanField(null=True,blank=True,default=False)
    date_created = models.DateField(auto_now_add=True)
    cover = models.ImageField(upload_to='cover', null=True, blank=True)
    # def __str__(self):
    #     return self.id

    class Meta:
        db_table = "document"       

class Progress(models.Model):
    document = models.OneToOneField(Document,on_delete=models.CASCADE,null=True,blank=True)
    #staff = models.ForeignKey(Staff,on_delete=models.CASCADE,null=True,blank=True)
    prog = models.IntegerField(default=0,null=True,blank=True)
    #comments = models.TextField(max_length=100,null=True,blank=True) 
    date_created = models.DateField(auto_now_add=True)
    
    status = models.BooleanField(null=True,blank=True,default=False)
    
    def __str__(self):
        return str(self.prog)

    class Meta:
        db_table = "progress"  
        
class Submission(models.Model):
    when = models.DateTimeField(auto_now=False,auto_now_add=False)
    level = models.ForeignKey(Level,on_delete=models.CASCADE, null=True,blank=True)
    academic_year =  models.CharField(max_length=50,null=True,blank=True,default=date)
    status = models.BooleanField(default=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE, null=True,blank=True)
    class Meta:
        db_table = "submission"

class Likes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    document = models.ManyToManyField(Document)
    class Meta:
        db_table = "Likes"
    # class Meta:
    #     default_permissions = ('')
    #     permissions = (('like_document','Can like documents'),('can_hire','Can hire employees'),('hire','Can employees'))
    # staff = models.OneToOneField(Staff,on_delete=models.CASCADE,null=True,blank=True)
    

archives/templates/includes/footer.html
{% load static %}
<!-- Footer -->
    <!-- START PAGE CONTENT-->
    
    <!-- END PAGE CONTENT-->
    {% comment %} <footer class="page-footer" style="justify-content: center">
        <div class="font-13">2022 © <b>DIT</b> - All rights reserved.</div>
      
        <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
    </footer> {% endcomment %}
<div>
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
  
<script src="{% static 'assets/vendors/jquery/dist/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/popper.js/dist/umd/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/metisMenu/dist/metisMenu.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- PAGE LEVEL PLUGINS-->
    <script src="{% static 'assets/vendors/chart.js/dist/Chart.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-2.0.3.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-us-aea-en.js' %}" type="text/javascript"></script>
    <!-- CORE SCRIPTS-->
    <script src="{% static 'assets/js/app.min.js' %}" type="text/javascript"></script>
    <!-- PAGE LEVEL SCRIPTS-->
    <script src="{% static 'assets/js/scripts/dashboard_1_demo.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/vendors/DataTables/datatables.min.js' %}" type="text/javascript"></script>

    
      <script>
        const disabledKeys = ["c", "C", "x", "J", "u", "I"]; // keys that will be disabled
      
        const showAlert = e => {
          e.preventDefault(); // preventing its default behaviour
          return alert("Sorry, you can't view or copy source codes this way!");
        }
      
        document.addEventListener("contextmenu", e => {
          showAlert(e); // calling showAlert() function on mouse right click
        });
      
        document.addEventListener("keydown", e => {
          // calling showAlert() function, if the pressed key matched to disabled keys
          if((e.ctrlKey && disabledKeys.includes(e.key)) || e.key === "F12") {
            showAlert(e);
          }
        });
      </script>
        <script>
            function AddTableARIA() {
                try {
                  var allTables = document.querySelectorAll("table");
                  for (var i = 0; i < allTables.length; i++) {
                    allTables[i].setAttribute("role", "table");
                  }
                  var allRowGroups = document.querySelectorAll("thead, tbody, tfoot");
                  for (var i = 0; i < allRowGroups.length; i++) {
                    allRowGroups[i].setAttribute("role", "rowgroup");
                  }
                  var allRows = document.querySelectorAll("tr");
                  for (var i = 0; i < allRows.length; i++) {
                    allRows[i].setAttribute("role", "row");
                  }
                  var allCells = document.querySelectorAll("td");
                  for (var i = 0; i < allCells.length; i++) {
                    allCells[i].setAttribute("role", "cell");
                  }
                  var allHeaders = document.querySelectorAll("th");
                  for (var i = 0; i < allHeaders.length; i++) {
                    allHeaders[i].setAttribute("role", "columnheader");
                  }
                  // this accounts for scoped row headers
                  var allRowHeaders = document.querySelectorAll("th[scope=row]");
                  for (var i = 0; i < allRowHeaders.length; i++) {
                    allRowHeaders[i].setAttribute("role", "rowheader");
                  }
                  // caption role not needed as it is not a real role and
                  // browsers do not dump their own role with display block
                } catch (e) {
                  console.log("AddTableARIA(): " + e);
                }
              }
              
              AddTableARIA();
              
              const MAX_COLS = 5;
              const MIN_COLS = 2;
              
              function cropTable(visibleCols) {
                const table = document.querySelector("figure");
                const { width: tableWidth } = table.getBoundingClientRect();
                const cols = table.querySelectorAll("th, td");
                const newWidth = tableWidth / visibleCols;
              
                // Resize columns to fit table
                cols.forEach(function (col) {
                  // Always make sure that col is cropped by at least 15%
                  col.style.minWidth = newWidth + (newWidth * 0.15) + "px";
                });
              
                // Return if we are about to fall below min column count
                if (visibleCols <= MIN_COLS) {
                  return;
                }
              
                // Measure a sample table column to check if resizing was successful
                const { width: colWidth } = cols[0].getBoundingClientRect();
              
                // Check if we should crop to 1 column less (calculate new column width)
                if (colWidth * visibleCols > tableWidth + newWidth * 0.95) {
                  cropTable(visibleCols - 1);
                }
              }
              
              window.addEventListener("resize", function () {
                cropTable(MAX_COLS);
              });
              
              cropTable(MAX_COLS);
        
        
        </script>

        <script>
          $(document).ready(function() {
            var table = $('#data-table').DataTable({
              "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
              "columnDefs": [{
                "searchable": false,
                "orderable": false,
                "targets": [2]
              }],
              "order": [[4, 'desc']],
              "buttons": [
                {
                  extend: 'excel',
                  text: 'Export to Excel',
                  exportOptions: {
                    modifier: {
                      search: 'applied'
                    }
                  }
                }
              ]
            });
        
            $('#data-table thead tr:eq(1) th').each(function() {
              var title = $(this).text();
              $(this).html('<input type="text" placeholder="Search ' + title + '" />');
            });
          }); 
        </script>
        
        <script>
          $(document).ready(function() {
              var table = $('#data-tableb').DataTable({
                  "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                "columnDefs": [{
                  "searchable": false,
                  "orderable": false,
                  "targets": [2]
                }],
                "order": [
                  [3, 'asc']
                ]
              });
            
              $('#data-tableb thead tr:eq(1) th').each(function() {
                var title = $(this).text();
                $(this).html('<input type="text" placeholder="Search ' + title + '" />');
              });
            
            
            }); 
      </script>
        <script>
          $(document).ready(function() {
              var table = $('#data-tables').DataTable({
                  "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                "columnDefs": [{
                  "searchable": false,
                  "orderable": false,
                  "targets": [2]
                }],
                "order": [
                  [3, 'asc']
                ]
              });
            
              $('#data-tables thead tr:eq(1) th').each(function() {
                var title = $(this).text();
                $(this).html('<input type="text" placeholder="Search ' + title + '" />');
              });
            
            
            }); 
      </script>

      <script>
        $(document).ready(function() {
            var table = $('#data-tablez').DataTable({
                "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
              "columnDefs": [{
                "searchable": false,
                "orderable": false,
                "targets": [2]
              }],
              "order": [
                [0, 'asc']
              ]
            });
          
            $('#data-tablez thead tr:eq(1) th').each(function() {
              var title = $(this).text();
              $(this).html('<input type="text" placeholder="Search ' + title + '" />');
            });
          
          
          }); 
    </script>
    <script>
      $(document).ready(function() {
          var table = $('#data-tablex').DataTable({
              "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            "columnDefs": [{
              "searchable": false,
              "orderable": false,
              "targets": [2]
            }],
            "order": [
              [0, 'asc']
            ]
          });
        
          $('#data-tablex thead tr:eq(1) th').each(function() {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
          });
        
        
        }); 
  </script>

  <script>
    $(document).ready(function() {
        var table = $('#data').DataTable({
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
          "columnDefs": [{
            "searchable": false,
            "orderable": false,
            "targets": [2]
          }],
          "order": [
            [0, 'asc']
          ]
        });
      
        $('#data thead tr:eq(1) th').each(function() {
          var title = $(this).text();
          $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });
      
      
      }); 
</script>


    <script>
      $(document).ready(function() {
          var table = $('#data-tabler').DataTable({
              "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
            "columnDefs": [{
              "searchable": false,
              "orderable": false,
              "targets": [2]
            }],
            "order": [
              [0, 'asc']
            ]
          });
        
          $('#data-tabler thead tr:eq(1) th').each(function() {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
          });
        
        
        }); 
  </script>

  <script>
    $(document).ready(function() {
        var table = $('#myTablek').DataTable({
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
          "columnDefs": [{
            "searchable": false,
            "orderable": false,
            "targets": [2]
          }],
          "order": [
            [4, 'desc']
          ],
          
          
        });
      
        $('#myTablek thead tr:eq(1) th').each(function() {
          var title = $(this).text();
          $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });
      
      
      }); 
</script>
</div>


</body>

</html>

archives/templates/includes/messages.html
{% load static %}
{% if messages %}
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
        }, 5000);
    </script>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show md-6" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

archives/templates/includes/sidebar.html
{% load static %}
<nav class="page-sidebar" id="sidebars">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                {% if request.user.is_staff %}
                <img src="{{request.user.staff.photo.url}}" width="45px" />
                   {% else %}   
                   <img src="{{request.user.student.photo.url}}" width="45px" />
                   {% endif %}
            </div>
            <div class="admin-info">
                <div class="font-strong">{{request.user.first_name}} </div><small>{{request.user.student.course}}</small></div>
        </div>
        <ul class="side-menu metismenu">
            
            <li>
                <a class="{% if side == 'dashboard' %} active {% endif %}" href="/"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
                <i class="fa-duotone fa-screen-users"></i>
            </li>
            {% if perms.archives.add_user%}
            <li class="{% if side == 'being' %} active {% elif side == 'staff' %} active  {% elif side == 'role' %} active {% endif %}">
                <a href="javascript:;" class="{% if side == 'being' %} active {% elif side == 'staff' %} active {% endif %}"><i class="sidebar-item-icon fa fa-user-circle-o"></i>
                    <span class="nav-label">User Management</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse"> 
            <li>
                {% comment %} <a href="javascript:;" class="{% if side == 'being'  %} active {% elif side == 'od'  %} active {% endif %}"><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Student Management</span><i class="fa fa-angle-left arrow"></i></a> {% endcomment %}
                
                    
                        <a class="{% if side == 'being' %} active {% endif %}" href="/student" ><i class="sidebar-item-icon fa fa-mortar-board"></i>
                            <span class="nav-label">Student Management</span>
                        </a>
                        
                   
                    {% comment %} <li>
                        <a class="{% if side == 'od' %} active {% endif %}" href="/student_od" >OD</a>
                    </li> {% endcomment %}
                
            </li>
            <li class="{% if side == 'staff' %} active {% endif %}">
                <a class="{% if side == 'staff' %} active {% endif %}" href="/staff" class=""><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Staff Management</span></i></a>
                {% comment %} <ul class="nav-2-level collapse">
                    <li>
                        <a href="/" >BEING</a>
                    </li>
                    <li>
                        <a class="" href="/" >OD</a>
                    </li>
                </ul> {% endcomment %}
            </li>
            <li class="{% if side == 'role' %} active {% endif %}">
                <a class="{% if side == 'role' %} active {% endif %}" href="/manageroles" class=""><i class="sidebar-item-icon fa fa-drivers-license-o"></i>
                    <span class="nav-label">Roles Management</span></i></a>
                {% comment %} <ul class="nav-2-level collapse">
                    <li>
                        <a href="/" >BEING</a>
                    </li>
                    <li>
                        <a class="" href="/" >OD</a>
                    </li>
                </ul> {% endcomment %}
            </li>
        </ul>
    </li>
    {% endif %}
    {% if perms.archives.view_document %}
            <li class="{% if side == 'upload_project' %} active {% elif side == 'projects' %} active {% elif side == 'manage_project'%} active {% elif side == 'assessment'%} active {% endif %} ">
                <a href="javascript:;" class="{% if side == 'upload_project' %} active {% elif side == 'project' %} active {% elif side == 'manage_project' %} active {% elif side == 'assessment'%} active {% endif %}"><i class="sidebar-item-icon fa fa-book"></i>
                    <span class="nav-label">Project Management</span><i class="fa fa-angle-left arrow"></i></a>
                <ul class="nav-2-level collapse"> 
                    <li class="{% if side == 'projects' %} active {% endif %}">
                        <a class="{% if side == 'projects' %} active {% endif %}" href="/projects" class=""><i class="sidebar-item-icon fa fa-eye"></i>
                            <span class="nav-label">View Project</span></i></a>
                        
                    </li>
                    {% if perms.archives.add_document  %}
            <li class="{% if side == 'upload_project' %} active {% endif %}">
                <a class="{% if side == 'upload_project' %} active {% endif %}" href="/pdf_upload" class=""><i class="sidebar-item-icon fa fa-cloud-upload"></i>
                    <span class="nav-label">Upload Project</span></i></a>
               
            </li>
            {% endif %}
            {% if perms.archives.change_document %}
            <li class="{% if side == 'manage_project' %} active {% endif %}">
                <a class="{% if side == 'manage_project' %} active {% endif %}" href="/manage_project" class=""><i class="sidebar-item-icon fa fa-database"></i>
                    <span class="nav-label">Manage Project</span></i></a>
               
            </li>

            {% endif %}
            {% if perms.archives.add_progress %}
            <li class="{% if side == 'assessment' %} active {% endif %}">
                <a class="{% if side == 'assessment' %} active {% endif %}" href="/assessment" class=""><i class="sidebar-item-icon fa fa-bar-chart"></i>
                    <span class="nav-label">Project Submission</span></i></a>
               
            </li>
            {% endif %}
                </ul>
            </li>
            {% endif %}
            {% if perms.archives.view_department%}
            <li>
                <a href="{% url 'department' %}" class="{% if side == 'department' %} active {% endif %}"><i class="sidebar-item-icon fa fa-university"></i>
                    <span class="nav-label">Department</span></i></a>
                </li>
                {% endif %}
                {% if perms.archives.view_level%}
                <li>
                    <a href="{% url 'level' %}"class="{% if side == 'level' %} active {% endif %}"><i class="sidebar-item-icon fa fa-bookmark"></i>
                        <span class="nav-label">Academic Level</span></i></a>
                    </li>
                    {% endif %}
                    {% if perms.archives.add_project_type%}
                    <li>
                        <a href="{% url 'project_type' %}" class="{% if side == 'project_type' %} active {% endif %}"><i class="sidebar-item-icon fa fa-sitemap"></i>
                            <span class="nav-label">Project type</span></i></a>
                        </li>
                        {% endif %}
            {% comment %} <li class="heading">FEATURES</li>
            <li>
                <a href="/" class=""><i class="sidebar-item-icon fa fa-shield"></i>
                    <span class="nav-label">System Setting</span></i></a>
                </li> {% endcomment %}
            
        </ul>
    </div>
</nav>
<style>

    .page-sidebar {
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        {% comment %} width: 250px; {% endcomment %}
        overflow-y: auto;
       
        z-index: 9999;
      }
      
</style>
<div class="content-wrapper">
    

   